name = "Llama-3.1-8B-Instruct"
release_date = "2025-06-11"
last_updated = "2026-04-17"
attachment = false
reasoning = false
tool_call = true
structured_output = true
temperature = true
open_weights = true

[cost]
input = 0.1
output = 0.1

[limit]
context = 131_072
output = 131_072

[modalities]
input = ["text"]
output = ["text"]
