name = "Llama-3.3-70B-Instruct"
release_date = "2025-04-01"
last_updated = "2026-04-17"
attachment = false
reasoning = false
tool_call = true
structured_output = true
temperature = true
open_weights = true

[cost]
input = 0.67
output = 0.67

[limit]
context = 131_072
output = 131_072

[modalities]
input = ["text"]
output = ["text"]
