name = "Qwen3Guard-Gen-8B"
release_date = "2025-04-16"
last_updated = "2025-04-16"
attachment = false
reasoning = false
tool_call = false
structured_output = false
temperature = true
open_weights = true

[cost]
input = 0.00
output = 0.00

[limit]
context = 32_768
output = 32_768

[modalities]
input = ["text"]
output = ["text"]
